# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Princess Promotion"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: uc980319@naver.com
#blog logo
logo: "/assets/images/logo_0116.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cover_0116.jpg"

name: 'uc980319'
author: 'uc980319'
author_image: "/assets/images/Face_0116.png"

paginate:	5

url: #"http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: #'@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	#https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	#https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/uc980319
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	#https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
